import { BadRequestException, Injectable, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHash } from 'crypto';
export type StoredFile = { url:string; publicId:string; filename:string; mimeType:string; size:number };
type UploadFile = { buffer:Buffer; originalname:string; mimetype:string; size:number };
@Injectable() export class StorageService {
  constructor(private readonly config:ConfigService) {}
  async uploadTaskAttachment(file:UploadFile):Promise<StoredFile> { const max=Number(this.config.get('MAX_UPLOAD_BYTES',5242880)); const allowed:string[]=(this.config.get<string>('ALLOWED_UPLOAD_MIME_TYPES')??'image/jpeg,image/png,image/webp,application/pdf').split(',').map((type:string)=>type.trim()); if(!file?.buffer)throw new BadRequestException('A file is required.'); if(file.size>max)throw new BadRequestException(`File must be ${max} bytes or smaller.`); if(!allowed.includes(file.mimetype))throw new BadRequestException('Unsupported file type.'); const cloud=this.config.get<string>('CLOUDINARY_CLOUD_NAME')?.trim(),key=this.config.get<string>('CLOUDINARY_API_KEY')?.trim(),secret=this.config.get<string>('CLOUDINARY_API_SECRET')?.trim(); if(!cloud||!key||!secret)throw new ServiceUnavailableException('File storage is not configured.'); const timestamp=Math.floor(Date.now()/1000),folder='task-management/attachments',signature=createHash('sha1').update(`folder=${folder}&timestamp=${timestamp}${secret}`).digest('hex'),name=this.safeFilename(file.originalname),bytes=file.buffer.buffer.slice(file.buffer.byteOffset,file.buffer.byteOffset+file.buffer.byteLength) as ArrayBuffer; const form=new FormData();form.append('file',new Blob([bytes],{type:file.mimetype}),name);form.append('api_key',key);form.append('timestamp',String(timestamp));form.append('folder',folder);form.append('signature',signature);let response:Response;try{response=await fetch(`https://api.cloudinary.com/v1_1/${cloud}/auto/upload`,{method:'POST',body:form})}catch{throw new ServiceUnavailableException('File storage is unavailable.')}if(!response.ok){const provider=await response.json().catch(()=>({})) as {error?:{message?:string}};throw new ServiceUnavailableException(this.providerMessage(provider.error?.message));}const payload=await response.json() as {secure_url:string;public_id:string};return {url:payload.secure_url,publicId:payload.public_id,filename:name,mimeType:file.mimetype,size:file.size}; }
  private safeFilename(name:string){return name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,180)||'attachment'}
  private providerMessage(message?:string){if(message?.toLowerCase().includes('cloud_name'))return 'File storage is misconfigured: use the exact Cloudinary Cloud Name from your dashboard.';if(message?.toLowerCase().includes('signature'))return 'File storage credentials are invalid. Verify the Cloudinary API key and API secret.';return 'File upload failed. Please try again later.'}
}
